### ISSUE TITLE
Long time no message falls out connection.

### ISSUE THREAD

**Issue by laikee99** [walkor/rabbitmq#6]
Hi, this problem is most of PHP rabbitMQ clients have.
It there any solutions that to re-connection or just prevent this situation appear? 
Thanks.

**Comment by walkor** [comment]
This library has a heartbeat to maintain connection. If the connection is interrupted, it will be reconnected

**Comment by laikee99** [comment]
> This library has a heartbeat to maintain connection. If the connection is interrupted, it will be reconnected

Got it, thanks
